// Auto-generated by svelte-origin
// Do not edit manually - regenerated on save

import type { SvelteComponent } from 'svelte';
import type { ColumnState } from './column-state.svelte.js';

/**
 * Props derived from ColumnState origin factory.
 * 
 * Bindable props: none
 * Generic parameters: <T, V>
 */
type __Props<T, V> = $origin.Props<ReturnType<typeof ColumnState<T, V>>>;

declare class __component<T, V> extends SvelteComponent<__Props<T, V>> {}
export default __component;
