// Auto-generated by svelte-origin
// Do not edit manually - regenerated on save

import type { SvelteComponent } from 'svelte';
import type { ExpandableState } from './expandable-state.svelte.js';

/**
 * Props derived from ExpandableState origin factory.
 * 
 * Bindable props: none
 * Generic parameters: <T>
 */
type __Props<T> = $origin.Props<ReturnType<typeof ExpandableState<T>>>;

declare class __component<T> extends SvelteComponent<__Props<T>> {}
export default __component;
