// Auto-generated by svelte-origin
// Do not edit manually - regenerated by 'svelte-origin generate-dts'

import type { SvelteComponent } from 'svelte';
import type { TableState } from './table-state.svelte.js';

/**
 * Props derived from TableState origin factory.
 * 
 * Bindable props: "data", "selected", "panel"
 * Generic parameters: <T>
 */
type __Props<T> = $origin.Props<ReturnType<typeof TableState<T>>>;

declare class __component<T> extends SvelteComponent<__Props<T>> {}
export default __component;
