// Auto-generated by svelte-origin
// Do not edit manually - regenerated by 'svelte-origin generate-dts'

import type { SvelteComponent } from 'svelte';
import type { ListState } from './list-state.svelte.js';

/**
 * Props derived from ListState origin factory.
 * 
 * Bindable props: "items"
 * Generic parameters: <T>
 */
type __Props<T> = $origin.Props<ReturnType<typeof ListState<T>>>;

declare class __component<T> extends SvelteComponent<__Props<T>> {}
export default __component;
