// Auto-generated by svelte-origin
// Do not edit manually - regenerated by 'svelte-origin generate-dts'

import type { SvelteComponent } from 'svelte';
import type { PanelState } from './panel-state.svelte.js';

/**
 * Props derived from PanelState origin factory.
 * 
 * Bindable props: none
 * Generic parameters: <T>
 */
type __Props<T> = $origin.Props<ReturnType<typeof PanelState<T>>>;

declare class __component<T> extends SvelteComponent<__Props<T>> {}
export default __component;
